name: homebrew

on:
  release:
    types: [published]
  workflow_dispatch: ~

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v2
        with:
          homebrew_owner: Justintime50
          homebrew_tap: homebrew-formulas
          github_token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit_owner: Justintime50
          commit_email: 39606064+Justintime50@users.noreply.github.com
          update_readme_table: true
          depends_on: 'python'
          install: 'virtualenv_install_with_resources'
          formula_includes: 'include Language::Python::Virtualenv'
          update_python_resources: true
