name: release

on:
  release:
    types: [published]
  workflow_dispatch: ~

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Build package
        run: just install build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release project to my Homebrew tap
        uses: Justintime50/homebrew-releaser@v2
        with:
          homebrew_owner: Justintime50
          homebrew_tap: homebrew-formulas
          github_token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit_owner: Justintime50
          commit_email: 39606064+Justintime50@users.noreply.github.com
          update_readme_table: true
          depends_on: 'python'
          install: 'virtualenv_install_with_resources'
          formula_includes: 'include Language::Python::Virtualenv'
          update_python_resources: true
